[project]
name = "fastapi-podman"
version = "0.1.0"
authors = [
    { name = "Angelos Panagiotopoulos", email = "angelospanag@protonmail.com" },
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.136.3",
]

[dependency-groups]
dev = ["httpx2>=2.3.0", "pytest>=9.0.3", "ruff>=0.15.16", "ty>=0.0.43"]

[tool.ruff]
lint.select = [
    "E",
    "W",
    "F",
    "B",
    "I",
    "N",
    "SIM",
    "UP",
    "PERF",
    "RET",
    "RSE",
]
